import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import { UserProvider } from "@/app/context/userProvider";
import { ToastProvider } from "../components/toast/page";
import { AppWrapper } from "@/app/context/appWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Tracking System - Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (

    <html lang="en">
      <body>
        <ToastProvider>
          <UserProvider>
            <AppWrapper>
              <div id="modal-root" />
              {children}
            </AppWrapper>
          </UserProvider>
        </ToastProvider>
      </body>
    </html>

  );
}
