'use client';

import jsPDF from 'jspdf';
import styles from './page.module.css';
import { useUser } from '@/app/context/userProvider';

export default function ProjectPDFReport({ project }: { project: any }) {
  const { user } = useUser();

  const getBase64FromUrl = (url: string): Promise<string> =>
    fetch(url)
      .then((res) => res.blob())
      .then(
        (blob) =>
          new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
          })
      );

  const downloadPDF = async () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const W = pdf.internal.pageSize.getWidth();   // 210
    const H = pdf.internal.pageSize.getHeight();  // 297
    const ML = 16;   // left margin
    const MR = 16;   // right margin
    const CW = W - ML - MR;
    let y = 0;
    let pageNum = 1;

    // ── Colour palette (black & white only) ──────────────────────────────
    const BLACK:      [number,number,number] = [0,   0,   0  ];
    const DARK:       [number,number,number] = [30,  30,  30 ];
    const MID:        [number,number,number] = [90,  90,  90 ];
    const LIGHT_GRAY: [number,number,number] = [200, 200, 200];
    const NEAR_WHITE: [number,number,number] = [245, 245, 245];
    const WHITE:      [number,number,number] = [255, 255, 255];

    // ── Helpers ───────────────────────────────────────────────────────────
    const setFont = (style: 'normal'|'bold'|'italic' = 'normal', size = 10) => {
      pdf.setFont('helvetica', style);
      pdf.setFontSize(size);
    };

    const setColor = (rgb: [number,number,number]) => pdf.setTextColor(...rgb);

    const checkBreak = (needed = 12) => {
      if (y + needed > H - 20) {
        drawFooter();
        pdf.addPage();
        pageNum++;
        drawRunningHeader();
      }
    };

    const hr = (color: [number,number,number] = LIGHT_GRAY, w = 0.2) => {
      pdf.setDrawColor(...color);
      pdf.setLineWidth(w);
      pdf.line(ML, y, W - MR, y);
    };

    const drawFooter = () => {
      // thin separator line
      pdf.setDrawColor(...LIGHT_GRAY);
      pdf.setLineWidth(0.2);
      pdf.line(ML, H - 12, W - MR, H - 12);

      setFont('normal', 7.5);
      setColor(MID);
      pdf.text('Project Tracking System — Confidential', ML, H - 7);
      pdf.text(`Page ${pageNum}`, W - MR, H - 7, { align: 'right' });
    };

    const drawRunningHeader = () => {
      // thin top bar
      pdf.setFillColor(...BLACK);
      pdf.rect(0, 0, W, 1, 'F');

      setFont('bold', 8);
      setColor(DARK);
      pdf.text('PROJECT TRACKING SYSTEM', ML, 9);

      setFont('normal', 8);
      setColor(MID);
      pdf.text(project?.name || '', W - MR, 9, { align: 'right' });

      pdf.setDrawColor(...LIGHT_GRAY);
      pdf.setLineWidth(0.2);
      pdf.line(ML, 12, W - MR, 12);

      y = 18;
    };

    // ══════════════════════════════════════════════════════════════════════
    // PAGE 1 HEADER
    // ══════════════════════════════════════════════════════════════════════

    // Top black bar (thin)
    pdf.setFillColor(...BLACK);
    pdf.rect(0, 0, W, 1.2, 'F');

    y = 10;

    // Logo
    try {
      const logoB64 = await getBase64FromUrl('/reportLogo.png');
      pdf.addImage(logoB64, 'PNG', ML, y, 36, 14);
    } catch {
      setFont('bold', 9);
      setColor(DARK);
      pdf.text('PTS', ML, y + 9);
    }

    // "PROJECT REPORT" — right-aligned
    setFont('bold', 18);
    setColor(BLACK);
    pdf.text('PROJECT REPORT', W - MR, y + 9, { align: 'right' });

    y += 18;

    // Thin separator
    hr(BLACK, 0.5);
    y += 1;

    // Sub-info line under separator
    setFont('normal', 8);
    setColor(MID);
    pdf.text(`Generated by: ${user?.name || ''}`, ML, y + 4.5);
    pdf.text(`${new Date().toLocaleString()}`, W - MR, y + 4.5, { align: 'right' });
    y += 10;

    // Bottom thin separator
    hr(LIGHT_GRAY, 0.15);
    y += 8;

    // ── Project name + status row ────────────────────────────────────────
    setFont('bold', 14);
    setColor(DARK);
    pdf.text(project?.name?.toUpperCase() || 'UNTITLED', ML, y);

    // Status — small caps, right-aligned, boxed
    const status = (project?.status || '—').toUpperCase();
    setFont('bold', 8);
    const sW = pdf.getTextWidth(status) + 8;
    pdf.setDrawColor(...BLACK);
    pdf.setLineWidth(0.4);
    pdf.rect(W - MR - sW, y - 5.5, sW, 7, 'S');
    setColor(BLACK);
    pdf.text(status, W - MR - sW / 2, y - 0.5, { align: 'center' });

    y += 10;
    hr(BLACK, 0.15);
    y += 10;

    // ══════════════════════════════════════════════════════════════════════
    // SECTION: PROJECT INFORMATION
    // ══════════════════════════════════════════════════════════════════════
    const sectionHeader = (title: string) => {
      checkBreak(16);
      setFont('bold', 8.5);
      setColor(MID);
      pdf.text(title.toUpperCase(), ML, y);
      y += 2;
      hr(BLACK, 0.4);
      y += 6;
    };

    const row = (label: string, value: string, col2Label?: string, col2Value?: string) => {
      checkBreak(8);
      const labelW = 36;
      const halfCW = CW / 2;

      setFont('bold', 9);
      setColor(MID);
      pdf.text(label, ML, y);

      setFont('normal', 9);
      setColor(DARK);
      const valLines = pdf.splitTextToSize(value || '—', halfCW - labelW - 4);
      pdf.text(valLines, ML + labelW, y);

      if (col2Label) {
        setFont('bold', 9);
        setColor(MID);
        pdf.text(col2Label, ML + halfCW + 4, y);

        setFont('normal', 9);
        setColor(DARK);
        const col2Lines = pdf.splitTextToSize(col2Value || '—', halfCW - labelW - 4);
        pdf.text(col2Lines, ML + halfCW + 4 + labelW - 8, y);
        y += Math.max(valLines.length, col2Lines.length) * 5.5 + 2;
      } else {
        y += valLines.length * 5.5 + 2;
      }
    };

    sectionHeader('Project Information');
    row('Manager',       project?.manager || '—',    'Business Unit', project?.businessUnit || '—');
    row('Start Date',    project?.startDate ? new Date(project.startDate).toLocaleDateString() : '—',
        'End Date',      project?.endDate   ? new Date(project.endDate).toLocaleDateString()   : '—');
    row('Created On',   project?.createDate  ? new Date(project.createDate).toLocaleDateString()  : '—',
        'Finish Date',   project?.finishDate ? new Date(project.finishDate).toLocaleDateString() : '—');
    row('Nature',        project?.nature || '—');

    if (project?.description) {
      checkBreak(12);
      setFont('bold', 9);
      setColor(MID);
      pdf.text('Description', ML, y);
      setFont('normal', 9);
      setColor(DARK);
      const descL = pdf.splitTextToSize(project.description, CW - 36);
      pdf.text(descL, ML + 36, y);
      y += descL.length * 5.5 + 2;
    }

    y += 6;

    // ══════════════════════════════════════════════════════════════════════
    // SECTION: TASKS
    // ══════════════════════════════════════════════════════════════════════
    sectionHeader(`Tasks  (${project?.tasks?.length || 0})`);

    const tasks: any[] = project?.tasks || [];

    if (tasks.length === 0) {
      setFont('italic', 9);
      setColor(MID);
      pdf.text('No tasks have been assigned to this project.', ML, y);
      y += 8;
    } else {
      tasks.forEach((task: any, i: number) => {
        const descLines = pdf.splitTextToSize(task.description || '—', CW - 32);
        const cardH = 8 + 5.5 * 2 + descLines.length * 5.5 + 8;
        checkBreak(cardH + 4);

        // Card: light gray fill, black border left stripe
        pdf.setFillColor(...NEAR_WHITE);
        pdf.setDrawColor(...LIGHT_GRAY);
        pdf.setLineWidth(0.15);
        pdf.rect(ML, y, CW, cardH, 'FD');

        // Left black accent stripe
        pdf.setFillColor(...BLACK);
        pdf.rect(ML, y, 1.5, cardH, 'F');

        const cx = ML + 5;   // content left
        const ty = y + 6;    // top content y inside card

        // Task index
        setFont('bold', 8.5);
        setColor(BLACK);
        pdf.text(`${String(i + 1).padStart(2, '0')}`, cx, ty);

        // Task name
        setFont('bold', 9.5);
        setColor(DARK);
        pdf.text(task.name || '—', cx + 9, ty);

        // Status — right side, small outlined box
        const tStatus = (task.status || 'Pending').toUpperCase();
        setFont('bold', 7.5);
        const tsW = pdf.getTextWidth(tStatus) + 6;
        pdf.setDrawColor(...BLACK);
        pdf.setLineWidth(0.3);
        pdf.rect(ML + CW - tsW - 1, ty - 5, tsW, 6.5, 'S');
        setColor(BLACK);
        pdf.text(tStatus, ML + CW - tsW - 1 + tsW / 2, ty - 0.3, { align: 'center' });

        // Row: Developer | Target Date
        const r2y = ty + 7;
        setFont('bold', 8.5);
        setColor(MID);
        pdf.text('Developer', cx + 9, r2y);
        setFont('normal', 8.5);
        setColor(DARK);
        pdf.text(task.developer || '—', cx + 9 + 22, r2y);

        setFont('bold', 8.5);
        setColor(MID);
        pdf.text('Target Date', cx + 9 + CW / 2 - 10, r2y);
        setFont('normal', 8.5);
        setColor(DARK);
        pdf.text(task.targetDate ? task.targetDate.slice(0, 10) : '—', cx + 9 + CW / 2 + 18, r2y);

        // Description
        if (task.description) {
          const r3y = r2y + 7;
          setFont('bold', 8.5);
          setColor(MID);
          pdf.text('Description', cx + 9, r3y);
          setFont('normal', 8.5);
          setColor(DARK);
          pdf.text(descLines, cx + 9 + 22, r3y);
        }

        y += cardH + 4;
      });
    }

    drawFooter();
    pdf.save(`Project_${project?.name || 'Report'}.pdf`);
  };

  // ── On-screen Preview ───────────────────────────────────────────────────
  return (
    <div className={styles.wrapper}>
      <div className={styles.paper}>

        {/* Header */}
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/reportLogo.png" alt="Logo" className={styles.logo} />
          </div>
          <div className={styles.headerRight}>
            <span className={styles.reportLabel}>PROJECT REPORT</span>
            <span className={styles.metaLine}>Generated by {user?.name} &nbsp;·&nbsp; {new Date().toLocaleDateString()}</span>
          </div>
        </div>

        <div className={styles.headerRule} />

        {/* Project title row */}
        <div className={styles.titleRow}>
          <h1 className={styles.projectName}>{project?.name?.toUpperCase()}</h1>
          <span className={styles.statusBox}>{project?.status?.toUpperCase()}</span>
        </div>

        <div className={styles.thinRule} />

        {/* Project info */}
        <div className={styles.section}>
          <p className={styles.sectionLabel}>PROJECT INFORMATION</p>
          <div className={styles.infoGrid}>
            {[
              ['Manager',       project?.manager],
              ['Business Unit', project?.businessUnit],
              ['Nature',        project?.nature],
              ['Status',        project?.status],
              ['Start Date',    project?.startDate ? new Date(project.startDate).toLocaleDateString() : '—'],
              ['End Date',      project?.endDate   ? new Date(project.endDate).toLocaleDateString()   : '—'],
              ['Created On',    project?.createDate  ? new Date(project.createDate).toLocaleDateString()  : '—'],
              ['Finish Date',   project?.finishDate ? new Date(project.finishDate).toLocaleDateString() : '—'],
            ].map(([l, v]) => (
              <div key={l as string} className={styles.infoRow}>
                <span className={styles.infoLabel}>{l}</span>
                <span className={styles.infoValue}>{v || '—'}</span>
              </div>
            ))}
            {project?.description && (
              <div className={`${styles.infoRow} ${styles.fullWidth}`}>
                <span className={styles.infoLabel}>Description</span>
                <span className={styles.infoValue}>{project.description}</span>
              </div>
            )}
          </div>
        </div>

        <div className={styles.thinRule} />

        {/* Tasks */}
        <div className={styles.section}>
          <p className={styles.sectionLabel}>TASKS &mdash; {project?.tasks?.length || 0}</p>
          {(project?.tasks || []).map((task: any, i: number) => (
            <div key={i} className={styles.taskCard}>
              <div className={styles.taskHeader}>
                <div className={styles.taskHeaderLeft}>
                  <span className={styles.taskIndex}>{String(i + 1).padStart(2, '0')}</span>
                  <span className={styles.taskNameText}>{task.name}</span>
                </div>
                <span className={styles.taskStatusBox}>{(task.status || 'Pending').toUpperCase()}</span>
              </div>
              <div className={styles.taskBody}>
                <div className={styles.infoRow}>
                  <span className={styles.infoLabel}>Developer</span>
                  <span className={styles.infoValue}>{task.developer || '—'}</span>
                </div>
                <div className={styles.infoRow}>
                  <span className={styles.infoLabel}>Target Date</span>
                  <span className={styles.infoValue}>{task.targetDate?.slice(0, 10) || '—'}</span>
                </div>
                {task.description && (
                  <div className={`${styles.infoRow} ${styles.fullWidth}`}>
                    <span className={styles.infoLabel}>Description</span>
                    <span className={styles.infoValue}>{task.description}</span>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>

      </div>

      <div className={styles.actions}>
        <button onClick={downloadPDF} className={styles.downloadBtn}>
          Download PDF
        </button>
      </div>
    </div>
  );
}
