import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MainScreen from "@/app/main/template/page";
import "@/app/globals.css"
import { UserProvider } from "@/app/context/userProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Tracking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <MainScreen>
        <UserProvider>
          {children}
        </UserProvider>
    </MainScreen>
  );
}
